language: node_js
node_js:
  - "node"
  - "iojs"
before_script:
  - "npm install istanbul"
  - "npm install codecov.io"
script: "./node_modules/.bin/istanbul cover ./test/all.js && cat ./coverage/lcov.info | ./node_modules/.bin/codecov"